### ISSUE TITLE
accessing environment variables in Angular

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#1]
I'm hitting third-party API endpoints on the client side of my app, and I'm struggling to access my API keys with Angular. I've created variables for them in my app.js, i.e. "var watson_key = process.env.WATSON_KEY;" and then did module.exports = watson_key. I've tried writing 'process.env.WATSON_KEY' directly in my Angular router. I've added the keys to my bash profile as well. 

It seems like I need to write a request from the client to the server to grab the key (http://stackoverflow.com/questions/33444300/angular-js-read-environmental-variables). 

Some other answers online talk about using grunt but I'm not excited to do that. Help? :)

**Comment by CentroDL** [comment]
env variables only exist server side, so you'd have to have your server make the api calls on the client's behalf

**Comment by rachelhamlin** [comment]
can I show you what I have?

On Tue, May 31, 2016 at 2:01 PM, Dennis Liaw notifications@github.com
wrote:

> env variables only exist server side, so you'd have to have your server
> make the api calls on the client's behalf
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/1#issuecomment-222769760,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY2fi-kHZtQmj80KWDI8YRj8We8ikks5qHHdygaJpZM4Iqj6H
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
currently using an Angular service to make the call.

On Tue, May 31, 2016 at 2:10 PM, Rachel Hamlin rachelmhamlin@gmail.com
wrote:

> can I show you what I have?
> 
> On Tue, May 31, 2016 at 2:01 PM, Dennis Liaw notifications@github.com
> wrote:
> 
> > env variables only exist server side, so you'd have to have your server
> > make the api calls on the client's behalf
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/rachelhamlin/MoodBling/issues/1#issuecomment-222769760,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AOwPY2fi-kHZtQmj80KWDI8YRj8We8ikks5qHHdygaJpZM4Iqj6H
> > .
> 
> ## 
> 
> Rachel Hamlin
> (315) 525-0537
> LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> https://twitter.com/rachelhamlin

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin
