### ISSUE TITLE
setting a global variable out of a post request in node/express config

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#3]
_Context:_ I'm using the client credential flow to get an access token for Spotify that I can use to hit some of their public playlist endpoints (specifically, to get the tracks from these playlists).

I need to set that token to a global variable that I can use in my other server-side routes for making the API calls.

_So far:_ I am following instructions to get a token in Node/Express, like so:

var authOptions = {
  url: 'https://accounts.spotify.com/api/token',
  headers: {
    'Authorization': 'Basic ' + (new Buffer(process.env.SPOTIFY_ID + ':' + process.env.SPOTIFY_SECRET).toString('base64'))
  },
  form: {
    grant_type: 'client_credentials'
  },
  json: true
};

request.post(authOptions, function(error, response, body){
  if (!error && response.statusCode === 200) {
    var token = body.access_token;
  }
})

This works to get a token.

_Problem:_ I'm not sure how to export the token as a variable that I can use in other files. 'require' ? I'm messing around with it now but I think it should be a quick solve.

**Comment by rachelhamlin** [comment]
Update: I still can't figure this s**\* out!

**Comment by rapala61** [comment]
in person
