### ISSUE TITLE
discuss IBM Alchemy -> Spotify algorithm

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#4]
I just want to chat with someone about the best approach to mapping the analysis of a user's mood (via IBM Alchemy) to a random track from Spotify.

IBM returns a score for 5 different emotions: anger, fear, sadness, disgust, and joy.

I could just take the the highest ranked emotion, sync it to a playlist, and grab a random track, but I want to do something a little more complex than that.

I was thinking I could either group the emotions and have a playlist for every combo of 2, so the 2 highest emotions would be registered. 

Or I might add an additional input where the user selects an emoji to rank how they're feeling, to weight the analysis in the right direction (but that kind of defeats the purpose).

Whatever I do, I need to define groups of playlists (or requests for playlists) from Spotify that match all the possible moods. 

Also: I need to figure out the best place to write the logic for this. I think I'll probably have a separate route on the back end for each possible mood. Then when the Alchemy analysis comes through on the client side, it can hit the corresponding playlist route for a song.

**Comment by DZGoldman** [comment]
I can talk this out

**Comment by rachelhamlin** [comment]
Coming to where you are!

On Wed, Jun 1, 2016 at 2:54 PM, Daniel Goldman notifications@github.com
wrote:

> I can talk this out
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/4#issuecomment-223090357,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY6NwaIYzqmE53y6KliYltyKTKgHOks5qHdV_gaJpZM4Ir2uG
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by DZGoldman** [comment]
done! (please close)
