### ISSUE TITLE
weird behavior from Angular functions

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#5]
In one of my Angular controllers, I'm trying to call one of a set of functions based on conditional logic.

These functions are written separately from the function that the logic resides in, e.g.:

 $scope.$on('emotion_data', function(event, data){

(lots of stuff)

if (emotion == 'anger') {
  $scope.runSpotifyAnger();
}

});

Then outside: 

$scope.runSpotifyAnger = function(){
console.log('anger');
}

But for some reason, every time I hit this controller now, I'm getting a TypeError that says "$scope.runSpotifyAnger is not a function": 

"angular.js:12520 TypeError: $scope.runSpotifyJoy is not a function
    at new <anonymous> (http://localhost:8080/js/results.js:56:10)
    at e (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:39:394)
    at Object.instantiate (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:40:9)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:80:442
    at A.link (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular-route.min.js:7:268)
    at ea (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:73:293)
    at D (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:62:190)
    at g (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:55:105)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:54:249
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:56:79 <div ng-view="" class="ng-scope">"

This happens regardless of whether I actually call the function or not.

I'm doing research but I have no idea why this is happening since I've written these functions the same way as any other.

**Comment by CentroDL** [comment]
load order! move it up above the method call. lemmeknow

**Comment by rachelhamlin** [comment]
Duuuuuuuhhh!!!!!!!! I'll let you know if it works

**Comment by rachelhamlin** [comment]
Hmmm no luck. I'm super confused!

On Thu, Jun 2, 2016 at 1:08 PM, Dennis Liaw notifications@github.com
wrote:

> load order! move it up above the method call. lemmeknow
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/5#issuecomment-223357032,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY1fGEwIE9BfYLGH-2HQVTvnzUAaOks5qHw34gaJpZM4IsvCm
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
This is so weird. I'm rewriting the functions with new, completely
different names and they're working. As long as '$scope' appears yellow
when I write them they work. For some reason in the first versions,
'$scope' was red. Possibly a conflict with another function whose name
started off the same way??

On Thu, Jun 2, 2016 at 1:08 PM, Dennis Liaw notifications@github.com
wrote:

> load order! move it up above the method call. lemmeknow
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/5#issuecomment-223357032,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY1fGEwIE9BfYLGH-2HQVTvnzUAaOks5qHw34gaJpZM4IsvCm
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin
