### ISSUE TITLE
wet code

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#6]
Helllllllp. I have a series of two functions on my server API responsible for 1) getting a Spotify playlist and then 2) tracks from that playlist.

The tracks function (#2) requires two arguments, playlist owner and playlist ID. I get those variables from the first function, the playlist function.

When I try to invoke the tracks function outside of the playlist function and pass it the two variables it needs, it doesn't work. I can only get it to work when I nest the two functions.

The issue is that I want to have 5 different playlist functions, but the tracks function always looks exactly the same and I don't want to write it 5 times. 🤔

**Comment by DZGoldman** [comment]
I can take a look in a few minutes

**Comment by rachelhamlin** [comment]
Okay! I'm at the long table.

On Thu, Jun 2, 2016 at 2:17 PM, Daniel Goldman notifications@github.com
wrote:

> I can take a look in a few minutes
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/6#issuecomment-223376723,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY9SJyppY_l-kHGB0zCrqaSy4ZYFrks5qHx4sgaJpZM4Is0sZ
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by DZGoldman** [comment]
Mind coming down to 3?

**Comment by rachelhamlin** [comment]
Hey, just came down. Where ya hiding?

On Thu, Jun 2, 2016 at 2:29 PM, Daniel Goldman notifications@github.com
wrote:

> Mind coming down to 3?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/6#issuecomment-223380234,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPYxsm8iWfFoo8RuIgmqWVWE_LDya7ks5qHyDvgaJpZM4Is0sZ
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by DZGoldman** [comment]
in the common room, by the windows

**Comment by DZGoldman** [comment]
done - please close!
