### ISSUE TITLE
weird CSS issue

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#7]
So I have two divs left and right of each other, the left side presents the mood of the user & the right side renders the song.

After a few times running the app, the right div with the album cover art and the song information collapses into the left div. Here's a pic:  https://www.dropbox.com/s/i89pquhb5rdu3tk/Screen%20Shot%202016-06-02%20at%207.07.05%20PM.png?dl=0

It's happening regularly.  Aaaaaaaash??? :)

**Comment by CentroDL** [comment]
ping me when you're in

**Comment by rachelhamlin** [comment]
hey dennis, i'm here

On Fri, Jun 3, 2016 at 11:02 AM, Dennis Liaw notifications@github.com
wrote:

> ping me when you're in
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/7#issuecomment-223603716,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPY1Sm_UW3uhwGmjtVEnLyZdrk0ZCEks5qIEIQgaJpZM4ItdXW
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
at the long table on the 4th floor

On Fri, Jun 3, 2016 at 11:16 AM, Rachel Hamlin rachelmhamlin@gmail.com
wrote:

> hey dennis, i'm here
> 
> On Fri, Jun 3, 2016 at 11:02 AM, Dennis Liaw notifications@github.com
> wrote:
> 
> > ping me when you're in
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/rachelhamlin/MoodBling/issues/7#issuecomment-223603716,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AOwPY1Sm_UW3uhwGmjtVEnLyZdrk0ZCEks5qIEIQgaJpZM4ItdXW
> > .
> 
> ## 
> 
> Rachel Hamlin
> (315) 525-0537
> LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> https://twitter.com/rachelhamlin

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin
