### ISSUE TITLE
how to handle access token expiration

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/MoodBling#8]
I use the client credential flow to get an access token for Spotify, and it lasts for 3600 seconds.

I don't have anything in place for when it expires. Right now, my app just gets stuck on the load screen and I see a 401 on my server. 

I know I could probably check the status code and if it's a 401, run the helper again for a new token, but I'm not positive about where to do the check or how to re-run the helper. Here is the helper:

  var authOptions = {
    url: 'https://accounts.spotify.com/api/token',
    headers: {
      'Authorization': 'Basic ' + (new Buffer(process.env.SPOTIFY_ID + ':' + process.env.SPOTIFY_SECRET).toString('base64'))
    },
    form: {
      grant_type: 'client_credentials'
    },
    json: true
  };

  request.post(authOptions, function(error, response, body){
    console.log(error, response.statusCode, body);

```
if (!error && response.statusCode === 200) {
  callback(body.access_token);
}
```

  })

And here is the start of the controller that uses the callback: 

var  spotifyHelper = require('../lib/spotifyhelper');

var spotify;
var playlistOwner;
var playlistId;

spotifyHelper(initSpotifyWebApi)

function initSpotifyWebApi( token ) {
  spotify = new spotifyWebAPI({
    clientID : '9d048b8d9f3e4dda8290122911457166',
    clientSecret : 'd0e1966e910146569a532b48eb51a27e',
    accessToken: token
  })
}

**ALSO -- I need to deploy this to Heroku today (since it's almost done -- just some styling left) and want to make sure I am able to work with my environment keys. So that's issue #2!**

**Comment by DZGoldman** [comment]
I can definitely help you get set up on heroku with your env variables. Taking a look at the access token stuff now

**Comment by rachelhamlin** [comment]
Okay! The latest version of the access stuff is all up.

On Fri, Jun 3, 2016 at 2:05 PM, Daniel Goldman notifications@github.com
wrote:

> I can definitely help you get set up on heroku with your env variables.
> Taking a look at the access token stuff now
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rachelhamlin/MoodBling/issues/8#issuecomment-223650673,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOwPYycDhNGCBgHPkR6Re9Jfayol5XkIks5qIGzTgaJpZM4ItwcP
> .

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
Looking into refresh tokens...
http://stackoverflow.com/questions/30372835/how-can-i-increase-the-expiry-time-of-spotify-token

On Fri, Jun 3, 2016 at 2:15 PM, Rachel Hamlin rachelmhamlin@gmail.com
wrote:

> Okay! The latest version of the access stuff is all up.
> 
> On Fri, Jun 3, 2016 at 2:05 PM, Daniel Goldman notifications@github.com
> wrote:
> 
> > I can definitely help you get set up on heroku with your env variables.
> > Taking a look at the access token stuff now
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/rachelhamlin/MoodBling/issues/8#issuecomment-223650673,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AOwPYycDhNGCBgHPkR6Re9Jfayol5XkIks5qIGzTgaJpZM4ItwcP
> > .
> 
> ## 
> 
> Rachel Hamlin
> (315) 525-0537
> LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> https://twitter.com/rachelhamlin

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin
